channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=26.0.1
- pip:
  - mlflow==3.10.0
  - cloudpickle==3.1.2
  - lz4==4.3.2
  - numpy==2.4.2
  - pandas==2.3.3
  - pathlib==1.0.1
  - psutil==7.2.2
  - pyarrow==23.0.1
  - scikit-learn==1.8.0
  - scipy==1.17.1
name: mlflow-env
